# Generated by Django 5.2.11 on 2026-02-11 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AffiliateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Fitness Equipment')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(help_text="URL-friendly name", unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Category description (appears on page)"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, help_text="SEO title tag", max_length=200
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO meta description (160 chars max)",
                        max_length=160,
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for SEO",
                        max_length=200,
                    ),
                ),
                (
                    "amazon_category_id",
                    models.CharField(
                        blank=True,
                        help_text="Amazon browse node ID for API queries",
                        max_length=50,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Featured image for category",
                        null=True,
                        upload_to="affiliate/categories/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DRAFT", "Draft"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in featured categories section"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order in category listings"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category (for subcategories)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="affiliate.affiliatecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affiliate Category",
                "verbose_name_plural": "Affiliate Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AffiliatePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Blog post title", max_length=300),
                ),
                ("slug", models.SlugField(help_text="URL slug", unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short preview text (appears in listings)",
                        max_length=500,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Main blog content (HTML allowed)"),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Featured image for blog post",
                        null=True,
                        upload_to="affiliate/blogs/",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, help_text="Post author name", max_length=200
                    ),
                ),
                (
                    "author_bio",
                    models.TextField(blank=True, help_text="Short author biography"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, help_text="SEO title tag", max_length=200
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, help_text="SEO meta description", max_length=160
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, help_text="Comma-separated keywords", max_length=200
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        default="Find a professional near you",
                        help_text="CTA text placeholder (will link to service pages in Phase 2)",
                        max_length=200,
                    ),
                ),
                (
                    "cta_service",
                    models.CharField(
                        blank=True,
                        help_text="Service name for CTA (e.g., 'Fitness Training')",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="When post was published", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "view_count",
                    models.IntegerField(default=0, help_text="Number of page views"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Which category this post belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="affiliate.affiliatecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affiliate Post",
                "verbose_name_plural": "Affiliate Posts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AffiliateProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asin",
                    models.CharField(
                        help_text="Amazon Standard Identification Number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Product title from Amazon", max_length=500
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Direct Amazon product link", max_length=500
                    ),
                ),
                (
                    "price_gbp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price in GBP",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_original",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original/list price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GBP", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True,
                        help_text="Average rating (0-5 stars)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(
                        default=0, help_text="Number of customer reviews"
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(default=True, help_text="Currently in stock"),
                ),
                (
                    "availability_text",
                    models.CharField(
                        blank=True,
                        help_text="Availability description from Amazon",
                        max_length=100,
                    ),
                ),
                (
                    "bsr_rank",
                    models.IntegerField(
                        blank=True, help_text="Best Seller Rank in category", null=True
                    ),
                ),
                (
                    "bsr_category",
                    models.CharField(
                        blank=True, help_text="Category for BSR", max_length=100
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Product image URL from Amazon",
                        max_length=500,
                    ),
                ),
                (
                    "last_verified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this product data was verified",
                    ),
                ),
                (
                    "added_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this product was first added"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DISCONTINUED", "Discontinued"),
                            ("OUT_OF_STOCK", "Out of Stock"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, help_text="Full API response from Amazon", null=True
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        help_text="Which categories this product appears in",
                        related_name="products",
                        to="affiliate.affiliatecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affiliate Product",
                "verbose_name_plural": "Affiliate Products",
                "ordering": ["-rating", "-review_count"],
            },
        ),
        migrations.CreateModel(
            name="AffiliateProductCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cached_asins",
                    models.JSONField(
                        default=list,
                        help_text="List of ASIN codes for eligible products in this category",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this cache was last refreshed"
                    ),
                ),
                (
                    "next_refresh",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this cache should be refreshed next",
                        null=True,
                    ),
                ),
                (
                    "is_fresh",
                    models.BooleanField(
                        default=False, help_text="Whether cache is fresh enough to use"
                    ),
                ),
                (
                    "product_count",
                    models.IntegerField(
                        default=0, help_text="Number of products in cache"
                    ),
                ),
                (
                    "uses_parent_fallback",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this cache uses parent category products as fallback",
                    ),
                ),
                (
                    "parent_fallback_asins",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Parent category product ASINs (fallback only)",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Last error encountered during refresh"
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        default=0, help_text="Number of consecutive refresh failures"
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        help_text="Category this cache is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_product_cache",
                        to="affiliate.affiliatecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affiliate Product Cache",
                "verbose_name_plural": "Affiliate Product Caches",
            },
        ),
        migrations.CreateModel(
            name="AffiliateProductFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_rating",
                    models.FloatField(
                        default=4.0,
                        help_text="Minimum average rating required",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "min_review_count",
                    models.IntegerField(
                        default=200,
                        help_text="Minimum number of reviews required",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_bsr_percentile",
                    models.IntegerField(
                        default=10,
                        help_text="Top X% of category by BSR (lower = more exclusive)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "uk_marketplace_only",
                    models.BooleanField(
                        default=True,
                        help_text="Only products available in UK marketplace",
                    ),
                ),
                (
                    "in_stock_only",
                    models.BooleanField(
                        default=True, help_text="Only in-stock products"
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum acceptable price (GBP)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum acceptable price (GBP)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether these filter rules are currently applied",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.OneToOneField(
                        help_text="Category these filter rules apply to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_rules",
                        to="affiliate.affiliatecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affiliate Product Filter",
                "verbose_name_plural": "Affiliate Product Filters",
            },
        ),
        migrations.AddIndex(
            model_name="affiliatecategory",
            index=models.Index(fields=["slug"], name="affiliate_a_slug_3e3b09_idx"),
        ),
        migrations.AddIndex(
            model_name="affiliatecategory",
            index=models.Index(
                fields=["status", "display_order"], name="affiliate_a_status_7b1be1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliatecategory",
            index=models.Index(
                fields=["parent", "status"], name="affiliate_a_parent__9f1978_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliatepost",
            index=models.Index(fields=["slug"], name="affiliate_a_slug_e4db0b_idx"),
        ),
        migrations.AddIndex(
            model_name="affiliatepost",
            index=models.Index(
                fields=["category", "status"], name="affiliate_a_categor_6fbd67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliatepost",
            index=models.Index(
                fields=["-published_at"], name="affiliate_a_publish_5d0804_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliatepost",
            index=models.Index(fields=["status"], name="affiliate_a_status_b2d8f0_idx"),
        ),
        migrations.AddIndex(
            model_name="affiliateproduct",
            index=models.Index(fields=["asin"], name="affiliate_a_asin_dd6540_idx"),
        ),
        migrations.AddIndex(
            model_name="affiliateproduct",
            index=models.Index(
                fields=["status", "in_stock"], name="affiliate_a_status_dd2146_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliateproduct",
            index=models.Index(
                fields=["rating", "review_count"], name="affiliate_a_rating_a19647_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliateproduct",
            index=models.Index(
                fields=["-added_date"], name="affiliate_a_added_d_ea1867_idx"
            ),
        ),
    ]
