# Generated by Django 5.2.11 on 2026-02-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Setting key (e.g., 'MIN_PRODUCT_RATING')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("value", models.TextField(help_text="Setting value (can be JSON)")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this setting does"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        help_text="Data type for validation",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
            },
        ),
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_name",
                    models.CharField(
                        choices=[
                            ("AMAZON", "Amazon Product Advertising API"),
                            ("TWILIO", "Twilio API"),
                            ("INTERNAL", "Internal API"),
                        ],
                        help_text="Which API was called",
                        max_length=50,
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(help_text="API endpoint called", max_length=300),
                ),
                (
                    "method",
                    models.CharField(
                        default="GET",
                        help_text="HTTP method (GET, POST, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, help_text="HTTP response status code", null=True
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if request failed"
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True,
                        help_text="Request parameters (sanitized)",
                        null=True,
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, help_text="Response data (first 1KB)", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "API Log",
                "verbose_name_plural": "API Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["api_name", "-created_at"],
                        name="core_apilog_api_nam_d606d0_idx",
                    ),
                    models.Index(
                        fields=["status_code"], name="core_apilog_status__093590_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_name",
                    models.CharField(
                        help_text="Name of the service (e.g., 'Fitness Training', 'Nutrition Coaching')",
                        max_length=200,
                    ),
                ),
                (
                    "service_slug",
                    models.SlugField(
                        help_text="URL-friendly version of service name", unique=True
                    ),
                ),
                (
                    "service_description",
                    models.TextField(
                        blank=True, help_text="Description of what this service entails"
                    ),
                ),
                (
                    "city_name",
                    models.CharField(
                        help_text="City name (e.g., 'London', 'Manchester')",
                        max_length=100,
                    ),
                ),
                (
                    "city_slug",
                    models.SlugField(help_text="URL-friendly version of city name"),
                ),
                (
                    "page_slug",
                    models.SlugField(
                        help_text="Combined slug for page URL: service-city",
                        unique=True,
                    ),
                ),
                (
                    "local_areas",
                    models.TextField(
                        blank=True,
                        help_text="JSON or comma-separated list of areas/postcodes in this city",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Region/County (e.g., 'Greater London', 'Manchester Area')",
                        max_length=100,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="United Kingdom",
                        help_text="Country name",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PLANNED", "Planned"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="PLANNED",
                        help_text="Publication status",
                        max_length=20,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, help_text="SEO title tag", max_length=200
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, help_text="SEO meta description", max_length=160
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated SEO keywords",
                        max_length=200,
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        blank=True,
                        help_text="Page hero title (e.g., 'Best Fitness Training in London')",
                        max_length=200,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        blank=True, help_text="Page hero subtitle", max_length=300
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this service-city page is published",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this page was first published",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service × City",
                "verbose_name_plural": "Services × Cities",
                "ordering": ["service_name", "city_name"],
                "indexes": [
                    models.Index(
                        fields=["service_slug", "status"],
                        name="core_servic_service_1c2db4_idx",
                    ),
                    models.Index(
                        fields=["city_slug", "status"],
                        name="core_servic_city_sl_3a66bd_idx",
                    ),
                    models.Index(
                        fields=["page_slug"], name="core_servic_page_sl_6d2325_idx"
                    ),
                    models.Index(
                        fields=["status", "is_published"],
                        name="core_servic_status_cf04af_idx",
                    ),
                ],
                "unique_together": {("service_slug", "city_slug")},
            },
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_name",
                    models.CharField(
                        help_text="Name of the task (e.g., 'refresh_affiliate_products')",
                        max_length=200,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        help_text="Celery task ID", max_length=100, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("STARTED", "Started"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("RETRY", "Retry"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="How long the task took to complete",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if task failed"
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Task result data", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Log",
                "verbose_name_plural": "Task Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task_name", "-created_at"],
                        name="core_tasklo_task_na_56591c_idx",
                    ),
                    models.Index(
                        fields=["status"], name="core_tasklo_status_68e013_idx"
                    ),
                ],
            },
        ),
    ]
