# Generated by Django 5.2.11 on 2026-02-11 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Consumer name", max_length=200)),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Consumer email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Consumer phone number", max_length=20),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp number (if different from phone)",
                        max_length=20,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        help_text="Service consumer is interested in", max_length=200
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City where consumer wants service", max_length=100
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Any additional notes from consumer"
                    ),
                ),
                (
                    "provider_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Which provider is handling this lead (provider ID)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("QUALIFIED", "Qualified"),
                            ("CONVERTED", "Converted"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="NEW",
                        help_text="Lead status (QUALIFIED = billable)",
                        max_length=20,
                    ),
                ),
                (
                    "is_billed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether provider has been billed for this lead",
                    ),
                ),
                (
                    "billed_at",
                    models.DateTimeField(
                        blank=True, help_text="When this lead was billed", null=True
                    ),
                ),
                (
                    "amount_billed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount provider was charged (GBP)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qualified_at",
                    models.DateTimeField(
                        blank=True, help_text="When lead became qualified", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="leads_lead_status_e23abe_idx"
                    ),
                    models.Index(
                        fields=["provider_id", "status"],
                        name="leads_lead_provide_fe34f4_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="leads_lead_created_921505_idx"
                    ),
                    models.Index(
                        fields=["service", "city"], name="leads_lead_service_11dd2b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeadEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Lead Created"),
                            ("ASSIGNED", "Assigned to Provider"),
                            ("CONTACT_ATTEMPT", "Contact Attempt"),
                            ("CONTACT_SUCCESS", "Contact Successful"),
                            ("CONTACT_FAILED", "Contact Failed"),
                            ("QUALIFIED", "Lead Qualified"),
                            ("BILLED", "Lead Billed"),
                            ("CONVERTED", "Lead Converted"),
                            ("REJECTED", "Lead Rejected"),
                            ("EXPIRED", "Lead Expired"),
                        ],
                        help_text="Type of event",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Additional event details"),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System/Automation"),
                            ("PROVIDER", "Provider"),
                            ("ADMIN", "Admin"),
                            ("TWILIO", "Twilio Webhook"),
                        ],
                        default="SYSTEM",
                        help_text="Who triggered this event",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="Which lead this event is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Event",
                "verbose_name_plural": "Lead Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "-created_at"],
                        name="leads_leade_lead_id_dce62a_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="leads_leade_event_t_0987d8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TwilioCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_sid",
                    models.CharField(
                        help_text="Twilio call SID (unique identifier)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "from_number",
                    models.CharField(help_text="Caller ID number", max_length=20),
                ),
                (
                    "to_number",
                    models.CharField(help_text="Number that was called", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("RINGING", "Ringing"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("NO_ANSWER", "No Answer"),
                            ("BUSY", "Busy"),
                            ("VOICEMAIL", "Voicemail"),
                        ],
                        default="INITIATED",
                        help_text="Current call status",
                        max_length=20,
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Call duration in seconds (0 if not answered)",
                        null=True,
                    ),
                ),
                (
                    "recording_url",
                    models.URLField(
                        blank=True, help_text="URL to call recording (if available)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if call failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="Which lead this call is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="twilio_calls",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twilio Call",
                "verbose_name_plural": "Twilio Calls",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["call_sid"], name="leads_twili_call_si_9ea0d5_idx"
                    ),
                    models.Index(
                        fields=["status"], name="leads_twili_status_b3417d_idx"
                    ),
                    models.Index(
                        fields=["lead", "-created_at"],
                        name="leads_twili_lead_id_fbbe56_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TwilioMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_sid",
                    models.CharField(
                        help_text="Twilio message SID (unique identifier)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "from_number",
                    models.CharField(help_text="Sender number", max_length=20),
                ),
                (
                    "to_number",
                    models.CharField(help_text="Recipient number", max_length=20),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("SMS", "SMS"), ("WHATSAPP", "WhatsApp")],
                        default="SMS",
                        help_text="Type of message (SMS or WhatsApp)",
                        max_length=20,
                    ),
                ),
                ("message_body", models.TextField(help_text="Message content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        help_text="Message delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if delivery failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="Which lead this message is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="twilio_messages",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twilio Message",
                "verbose_name_plural": "Twilio Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["message_sid"], name="leads_twili_message_cab643_idx"
                    ),
                    models.Index(
                        fields=["status"], name="leads_twili_status_d4669b_idx"
                    ),
                    models.Index(
                        fields=["lead", "-created_at"],
                        name="leads_twili_lead_id_a7e296_idx",
                    ),
                ],
            },
        ),
    ]
