# Generated by Django 5.2.11 on 2026-02-11 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Provider/business name", max_length=200
                    ),
                ),
                ("email", models.EmailField(help_text="Contact email", max_length=254)),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False, help_text="Whether phone has been verified"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Official company name (if different from provider name)",
                        max_length=200,
                    ),
                ),
                (
                    "company_website",
                    models.URLField(blank=True, help_text="Provider's website"),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Professional biography"),
                ),
                (
                    "qualifications",
                    models.TextField(
                        blank=True, help_text="Certifications, degrees, experience"
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        default=list,
                        help_text="List of services provided (e.g., ['Fitness Training'])",
                    ),
                ),
                (
                    "cities",
                    models.JSONField(
                        default=list,
                        help_text="List of cities served (e.g., ['London', 'Manchester'])",
                    ),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[
                            ("PHONE", "Phone Call"),
                            ("EMAIL", "Email"),
                            ("WHATSAPP", "WhatsApp"),
                            ("SMS", "SMS"),
                            ("FORM", "Contact Form"),
                        ],
                        default="PHONE",
                        help_text="Preferred contact method",
                        max_length=20,
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("PAY_PER_LEAD", "Pay per qualified lead"),
                            ("PAY_PER_BOOKING", "Pay per booking"),
                            ("SUBSCRIPTION", "Monthly subscription"),
                        ],
                        default="PAY_PER_LEAD",
                        help_text="How provider is charged",
                        max_length=30,
                    ),
                ),
                (
                    "price_per_lead",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per qualified lead (GBP)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING_VERIFICATION", "Pending Verification"),
                        ],
                        default="PENDING_VERIFICATION",
                        help_text="Onboarding/activation status",
                        max_length=30,
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True,
                        help_text="Average rating from consumer feedback (0-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MinValueValidator(5),
                        ],
                    ),
                ),
                (
                    "total_leads_received",
                    models.IntegerField(
                        default=0,
                        help_text="Total qualified leads sent to this provider",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount paid by provider (GBP)",
                        max_digits=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When provider was verified", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="providers_p_email_ce41f7_idx"),
                    models.Index(
                        fields=["status"], name="providers_p_status_4e11d3_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="providers_p_created_98ceba_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        help_text="Service name (e.g., 'Fitness Training')",
                        max_length=200,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City name (e.g., 'London')", max_length=100
                    ),
                ),
                (
                    "price_for_this_location",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price override for this service-city combo (if different)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Currently accepting leads for this service-city",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Which provider this coverage applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Coverage",
                "verbose_name_plural": "Provider Coverages",
                "indexes": [
                    models.Index(
                        fields=["provider", "service"],
                        name="providers_p_provide_21ec16_idx",
                    ),
                    models.Index(
                        fields=["service", "city"],
                        name="providers_p_service_9235fe_idx",
                    ),
                ],
                "unique_together": {("provider", "service", "city")},
            },
        ),
    ]
